name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Initialize Terraform
        run: terraform init
        working-directory: terra-aws

      - name: Validate Terraform
        run: terraform validate
        working-directory: terra-aws

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: terra-aws
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          #TF_LOG: DEBUG

      - name: Apply Terraform
        run: terraform destroy -auto-approve tfplan
        working-directory: terra-aws
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

  fastapi-deploy:
    runs-on: ubuntu-latest
    needs: terraform-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn
        working-directory: fastapi

      - name: Package Application
        run: zip -r app.zip .
        working-directory: fastapi

      - name: Add SSH Private Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > fastapiapp-key.pem
          chmod 600 fastapiapp-key.pem

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          scp -o StrictHostKeyChecking=no -i fastapiapp-key.pem fastapi/app.zip ec2-user@fastapi_app:/home/ec2-user/app.zip
          ssh -o StrictHostKeyChecking=no -i fastapiapp-key.pem ec2-user@fastapi_app << 'EOF'
            sudo yum update -y
            sudo yum install python3 -y
            sudo pip3 install fastapi uvicorn
            unzip -o /home/ec2-user/app.zip -d /home/ec2-user/app
            nohup python3 -m uvicorn app.main:app --host 0.0.0.0 --port 80 &
          EOF
