name: Destroy AWS Resources

on:
  push:
    branches:
      - destroy

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Initialize Terraform
        run: terraform init
        working-directory: terra-aws

      - name: Select Terraform Workspace
        run: terraform workspace select main

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terra-aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
